---
title: "MVA_HW_3"
author: "aa2569@scarletmail.rutgers.edu"
date: "2/23/2023"
output: html_document
---
  

```{r}
library(readr)
library(SciViews)
library(scatterplot3d)
library(car)
library(lattice)
library(GGally)
library(ggplot2)
library(ggridges)
library(ggvis)
library(ggthemes)
library(cowplot)
library(gapminder)
library(gganimate)
library(dplyr)
library(tidyverse)
library(grid)
library(gridExtra)
library(RColorBrewer)
library(Hotelling)
library(stats)
library(biotools)
library(factoextra)
library(FactoMineR)
library(ggfortify)
library(psych)
library(corrplot)
library(devtools)

bm <- read_csv("/Users/ajayvishnu/Desktop/RUTGERS/Spring 2023/Multivariate Analysis/Datasets/Body_Measurements.csv")
bm
bm$Gender <- as.character(bm$Gender)
```

```{r}
one_bmd <- subset(bm, Gender == "1")
two_bmd <- subset(bm, Gender == "2")
one_bm <- one_bmd[,-1]
two_bm <- two_bmd[,-1]
colMeans(one_bm)
colMeans(two_bm)
```



```{r}
one_bm <- as.data.frame(one_bm)
cm_one_bm <- colMeans(one_bm)
cov_one_bm <- cov(one_bm)
d_one_bm <- apply(one_bm, MARGIN = 1, function(one_bm)t(one_bm - cm_one_bm) %*% solve(cov_one_bm) %*% (one_bm - cm_one_bm))
qqnorm(one_bm[,"Age"], main = "Age"); qqline(one_bm[,"Age"])
qqnorm(one_bm[,"HeadCircumference"], main = "HeadCircumference"); qqline(one_bm[,"HeadCircumference"])
qqnorm(one_bm[,"ShoulderWidth"], main = "ShoulderWidth"); qqline(one_bm[,"ShoulderWidth"])
qqnorm(one_bm[,"ChestWidth"], main = "ChestWidth"); qqline(one_bm[,"ChestWidth"])
qqnorm(one_bm[,"Belly"], main = "Belly"); qqline(one_bm[,"Belly"])
qqnorm(one_bm[,"Waist"], main = "Waist"); qqline(one_bm[,"Waist"])
qqnorm(one_bm[,"Hips"], main = "Hips"); qqline(one_bm[,"Hips"])
qqnorm(one_bm[,"ArmLength"], main = "ArmLength"); qqline(one_bm[,"ArmLength"])
qqnorm(one_bm[,"ShoulderToWaist"], main = "ShoulderToWaist"); qqline(one_bm[,"ShoulderToWaist"])
qqnorm(one_bm[,"WaistToKnee"], main = "WaistToKnee"); qqline(one_bm[,"WaistToKnee"])
qqnorm(one_bm[,"LegLength"], main = "LegLength"); qqline(one_bm[,"LegLength"])
qqnorm(one_bm[,"TotalHeight"], main = "TotalHeight"); qqline(one_bm[,"TotalHeight"])
```


```{r}
plot(qc <- qchisq((1:nrow(one_bm) - 1/2) / nrow(one_bm), df = 11), sd <- sort(d_one_bm),xlab = expression(paste(chi[12]^2, " Quantile")),ylab = "Ordered distances")
oups <- which(rank(abs(qc - sd), ties = "random") > nrow(one_bm) - 3)
text(qc[oups], sd[oups] - 1.5,oups)
abline(a = 0, b = 1)
```

```{r}
two_bm <- as.data.frame(two_bm)
cm_two_bm <- colMeans(two_bm)
cov_two_bm <- cov(two_bm)
d_two_bm <- apply(two_bm, MARGIN = 1, function(two_bm)t(two_bm - cm_two_bm) %*% solve(cov_two_bm) %*% (two_bm - cm_two_bm))
qqnorm(two_bm[,"Age"], main = "Age"); qqline(two_bm[,"Age"])
qqnorm(two_bm[,"HeadCircumference"], main = "HeadCircumference"); qqline(two_bm[,"HeadCircumference"])
qqnorm(two_bm[,"ShoulderWidth"], main = "ShoulderWidth"); qqline(two_bm[,"ShoulderWidth"])
qqnorm(two_bm[,"ChestWidth"], main = "ChestWidth"); qqline(two_bm[,"ChestWidth"])
qqnorm(two_bm[,"Belly"], main = "Belly"); qqline(two_bm[,"Belly"])
qqnorm(two_bm[,"Waist"], main = "Waist"); qqline(two_bm[,"Waist"])
qqnorm(two_bm[,"Hips"], main = "Hips"); qqline(two_bm[,"Hips"])
qqnorm(two_bm[,"ArmLength"], main = "ArmLength"); qqline(two_bm[,"ArmLength"])
qqnorm(two_bm[,"ShoulderToWaist"], main = "ShoulderToWaist"); qqline(two_bm[,"ShoulderToWaist"])
qqnorm(two_bm[,"WaistToKnee"], main = "WaistToKnee"); qqline(two_bm[,"WaistToKnee"])
qqnorm(two_bm[,"LegLength"], main = "LegLength"); qqline(two_bm[,"LegLength"])
qqnorm(two_bm[,"TotalHeight"], main = "TotalHeight"); qqline(two_bm[,"TotalHeight"])
```


```{r}
plot(qc1 <- qchisq((1:nrow(two_bm) - 1/2) / nrow(two_bm), df = 11), sd1 <- sort(d_two_bm),xlab = expression(paste(chi[11]^2, " Quantile")),ylab = "Ordered distances")
oups <- which(rank(abs(qc1 - sd1), ties = "random") > nrow(two_bm) - 3)
text(qc1[oups], sd1[oups] - 1.5,oups)
abline(a = 0, b = 1)
```

#####

```{r}
str(bm)
boxplot(bm[,-1])
stars(bm,labels = bm$Gender)
stars(one_bm, main = "Stars - 1")
stars(two_bm, main = "Stars - 2")
```

```{r}
pairs(bm[,-1])

bm_p <- data.frame(as.numeric(rownames(bm)),bm[,2:13])
labs.diagonal <- c("Person","HeadCircumference","HeadCircumference","ShoulderWidth","Chestwidth","Belly","Waist","Hips","ArmLength","ShoulderToWaist","WaistToKnee","LegLength")
pairs(bm_p, diag.panel = panel.boxplot, labels=labs.diagonal,pch=c(1,16),font.labels=2)
```

```{r}
defaultW <- getOption('warn')
options(warn = -1)
scatterplotMatrix(~Age+HeadCircumference+HeadCircumference+ShoulderWidth+ChestWidth+Belly+Waist+Hips+ArmLength+ShoulderToWaist+WaistToKnee+LegLength+TotalHeight | Gender, data=bm, var.labels=labs.diagonal,cex.labels=0.7, diagonal="boxplot",smooth=FALSE,reg.line=FALSE,pch=c(1,16),col=rep("black",2), legend.plot=FALSE)
options(warn = defaultW)
```

```{r}
super.sym <- trellis.par.get("superpose.symbol")
super.sym$superpose.symbol$pch <- c(1,16,rep(1,5))
super.sym$superpose.symbol$col <- rep("#000000",7)
trellis.par.set(super.sym)
splom(~bm_p, groups = Gender, data = bm, ps=0.5, varname.cex = .5,panel = panel.superpose,key = list(columns = 2,points = list(pch = super.sym$pch[1:2], col=super.sym$col[1:2]),text = list(c("1", "2"))))
```

```{r}
ggscatmat(bm, columns=2:13, color="Gender")
```

```{r}
ggplot(bm, aes(x=Gender,y=Age)) + geom_point(aes(col=Gender))
ggplot(bm, aes(x=Gender,y=HeadCircumference)) + geom_point(aes(col=Gender))
ggplot(bm, aes(x=Gender,y=ShoulderWidth)) + geom_point(aes(col=Gender))
ggplot(bm, aes(x=Gender,y=ChestWidth)) + geom_point(aes(col=Gender))
ggplot(bm, aes(x=Gender,y=Belly)) + geom_point(aes(col=Gender))
ggplot(bm, aes(x=Gender,y=Waist)) + geom_point(aes(col=Gender))
ggplot(bm, aes(x=Gender,y=Hips)) + geom_point(aes(col=Gender))
ggplot(bm, aes(x=Gender,y=ArmLength)) + geom_point(aes(col=Gender))
ggplot(bm, aes(x=Gender,y=ShoulderToWaist)) + geom_point(aes(col=Gender))
ggplot(bm, aes(x=Gender,y=WaistToKnee)) + geom_point(aes(col=Gender))
ggplot(bm, aes(x=Gender,y=LegLength)) + geom_point(aes(col=Gender))
ggplot(bm, aes(x=Gender,y=TotalHeight)) + geom_point(aes(col=Gender))
```

```{r}
bm_pca <- prcomp(bm[,-1],scale=TRUE)
bm_pca
summary(bm_pca)
```

```{r}
(eigen_bm <- bm_pca$sdev^2)
names(eigen_bm) <- paste("PC",1:5,sep="")
eigen_bm
sumlambdas <- sum(eigen_bm)
sumlambdas
propvar <- eigen_bm/sumlambdas
propvar
cumvar_bm <- cumsum(propvar)
cumvar_bm
matlambdas <- rbind(eigen_bm,propvar,cumvar_bm)
rownames(matlambdas) <- c("Eigenvalues","Prop. variance","Cum. prop. variance")
round(matlambdas,4)
summary(bm_pca)
bm_pca$rotation
print(bm_pca)
```

```{r}
attach(bm)
bm_pca$x
# Identifying the scores by their survival status
bmtyp_pca <- cbind(data.frame(Gender),bm_pca$x)
bmtyp_pca
# Means of scores for all the PC's classified by Survival status
tabmeansPC <- aggregate(bmtyp_pca[,2:13],by=list(Gender=bm$Gender),mean)
tabmeansPC
tabmeansPC <- tabmeansPC[rev(order(tabmeansPC$Gender)),]
tabmeansPC
tabfmeans <- t(tabmeansPC[,-1])
tabfmeans
colnames(tabfmeans) <- t(as.vector(tabmeansPC[1]$Gender))
tabfmeans
# Standard deviations of scores for all the PC's classified by Survival status
tabsdsPC <- aggregate(bmtyp_pca[,2:13],by=list(Gender=bm$Gender),sd)
tabfsds <- t(tabsdsPC[,-1])
colnames(tabfsds) <- t(as.vector(tabsdsPC[1]$Gender))
tabfsds
```

```{r}
t.test(PC1~bm$Gender,data=bmtyp_pca)
t.test(PC2~bm$Gender,data=bmtyp_pca)
t.test(PC3~bm$Gender,data=bmtyp_pca)
t.test(PC4~bm$Gender,data=bmtyp_pca)
t.test(PC5~bm$Gender,data=bmtyp_pca)
t.test(PC6~bm$Gender,data=bmtyp_pca)
t.test(PC7~bm$Gender,data=bmtyp_pca)
t.test(PC8~bm$Gender,data=bmtyp_pca)
t.test(PC9~bm$Gender,data=bmtyp_pca)
t.test(PC10~bm$Gender,data=bmtyp_pca)
t.test(PC11~bm$Gender,data=bmtyp_pca)
t.test(PC12~bm$Gender,data=bmtyp_pca)
## F ratio tests
var.test(PC1~bm$Gender,data=bmtyp_pca)
var.test(PC2~bm$Gender,data=bmtyp_pca)
var.test(PC3~bm$Gender,data=bmtyp_pca)
var.test(PC4~bm$Gender,data=bmtyp_pca)
var.test(PC5~bm$Gender,data=bmtyp_pca)
var.test(PC6~bm$Gender,data=bmtyp_pca)
var.test(PC7~bm$Gender,data=bmtyp_pca)
var.test(PC8~bm$Gender,data=bmtyp_pca)
var.test(PC9~bm$Gender,data=bmtyp_pca)
var.test(PC10~bm$Gender,data=bmtyp_pca)
var.test(PC11~bm$Gender,data=bmtyp_pca)
var.test(PC12~bm$Gender,data=bmtyp_pca)
```

```{r}
library(car)
(LTPC1 <- leveneTest(PC1~bm$Gender,data=bmtyp_pca))
(p_PC1_1sided <- LTPC1[[3]][1]/2)
(LTPC2 <- leveneTest(PC2~bm$Gender,data=bmtyp_pca))
(p_PC2_1sided=LTPC2[[3]][1]/2)
(LTPC3 <- leveneTest(PC3~bm$Gender,data=bmtyp_pca))
(p_PC3_1sided <- LTPC3[[3]][1]/2)
(LTPC4 <- leveneTest(PC4~bm$Gender,data=bmtyp_pca))
(p_PC4_1sided <- LTPC4[[3]][1]/2)
(LTPC5 <- leveneTest(PC5~bm$Gender,data=bmtyp_pca))
(p_PC5_1sided <- LTPC5[[3]][1]/2)
(LTPC6 <- leveneTest(PC6~bm$Gender,data=bmtyp_pca))
(p_PC6_1sided <- LTPC1[[3]][1]/2)
(LTPC7 <- leveneTest(PC7~bm$Gender,data=bmtyp_pca))
(p_PC7_1sided=LTPC2[[3]][1]/2)
(LTPC8 <- leveneTest(PC8~bm$Gender,data=bmtyp_pca))
(p_PC8_1sided <- LTPC3[[3]][1]/2)
(LTPC9 <- leveneTest(PC9~bm$Gender,data=bmtyp_pca))
(p_PC9_1sided <- LTPC4[[3]][1]/2)
(LTPC10 <- leveneTest(PC10~bm$Gender,data=bmtyp_pca))
(p_PC10_1sided <- LTPC5[[3]][1]/2)
(LTPC11 <- leveneTest(PC10~bm$Gender,data=bmtyp_pca))
(p_PC11_1sided <- LTPC5[[3]][1]/2)
(LTPC12 <- leveneTest(PC10~bm$Gender,data=bmtyp_pca))
(p_PC12_1sided <- LTPC5[[3]][1]/2)
# Plotting the scores for the first and second components
plot(bmtyp_pca$PC1, bmtyp_pca$PC2,pch=ifelse(bmtyp_pca$Gender == "S",1,16),xlab="PC1", ylab="PC2", main="49 bm against values for PC1 & PC2")
abline(h=0)
abline(v=0)
legend("bottomleft", legend=c("1","2"), pch=c(1,16))
plot(eigen_bm, xlab = "Component number", ylab = "Component variance", type = "l", main = "Scree diagram")
plot(log(eigen_bm), xlab = "Component number",ylab = "log(Component variance)", type="l",main = "Log(eigenvalue) diagram")
print(summary(bm_pca))
diag(cov(bm_pca$x))
xlim <- range(bm_pca$x[,1])
bm_pca$x[,1]
bm_pca$x
plot(bm_pca$x,xlim=xlim,ylim=xlim)
bm_pca$rotation[,1]
bm_pca$rotation
plot(bm[,-1])
bm_pca$x
```

```{r}
plot(bm_pca)
#get the original value of the data based on PCA
center <- bm_pca$center
scale <- bm_pca$scale
new_bm <- as.matrix(bm[,-1])
new_bm
drop(scale(new_bm,center=center, scale=scale)%*%bm_pca$rotation[,1])
predict(bm_pca)[,1]
#The aboved two gives us the same thing. predict is a good function to know.
bm$Gender <- as.factor(bm$Gender)
out <- sapply(1:12, function(i){plot(bm$Gender,bm_pca$x[,i],xlab=paste("PC",i,sep=""),ylab="Gender")})
pairs(bm_pca$x[,1:12], ylim = c(-6,4),xlim = c(-6,4),panel=function(x,y,...){text(x,y,bm$Gender)})
```


```{r}
# Correlation
pairs.panels(bm[,-1],
             gap = 0,
             bg = c("red", "blue")[bm$Gender],
             pch=21)

pairs.panels(bm_pca$x,
             gap=0,
             bg = c("red", "blue")[bm$Gender],
             pch=21)
```

```{r}
fviz_eig(bm_pca, addlabels = TRUE)
fviz_pca_var(bm_pca,col.var = "cos2",
             gradient.cols = c("#FFCC00", "#CC9933", "#660033", "#330033"),
             repel = TRUE)
fviz_pca_ind(bm_pca, col.ind = "cos2", 
                  gradient.cols = c("#FFCC00", "#CC9933", "#660033", "#330033"), 
                  repel = TRUE)
biplot(bm_pca)
autoplot(bm_pca,
         data = bm[,-1],
         loadings = TRUE,
         labels = bm$Gender)

# Different PCA Method. 
res.pca <- PCA(bm[,-1], graph = FALSE)
print(res.pca)

# Visualize and Interpret PCA using these functions 

#get_eigenvalue(res.pca): Extract the eigenvalues/variances of principal components
#fviz_eig(res.pca): Visualize the eigenvalues
#get_pca_ind(res.pca), get_pca_var(res.pca): Extract the results for individuals and variables, respectively.
#fviz_pca_ind(res.pca), fviz_pca_var(res.pca): Visualize the results individuals and variables, respectively.
#fviz_pca_biplot(res.pca): Make a biplot of individuals and variables.
```

```{r}
eig.val <- get_eigenvalue(res.pca)
eig.val

fviz_eig(res.pca, addlabels = TRUE, ylim = c(0, 50))

var <- get_pca_var(res.pca)
#var$coord: coordinates of variables to create a scatter plot
#var$cos2: represents the quality of representation for variables on the factor map. It’s calculated as the squared coordinates: var.cos2 = var.coord * var.coord.
#var$contrib: contains the contributions (in percentage) of the variables to the principal components. 
#The contribution of a variable (var) to a given principal component is (in percentage) : (var.cos2 * 100) / (total cos2 of the component).
var

# Coordinates
head(var$coord)
# Cos2: quality on the factore map
head(var$cos2)
# Contributions to the principal components
head(var$contrib)

#The plot Below is also known as variable correlation plots. It shows the relationships between all variables. It can be interpreted as follow:

#Positively correlated variables are grouped together.
#Negatively correlated variables are positioned on opposite sides of the plot origin (opposed quadrants).
#The distance between variables and the origin measures the quality of the variables on the factor map. 
#Variables that are away from the origin are well represented on the factor map.

# Correlation circle
fviz_pca_var(res.pca, col.var = "black")
```

```{r}
# Quality of representation


corrplot(var$cos2, is.corr=FALSE)
# Total cos2 of variables on Dim.1 and Dim.2
#A high cos2 indicates a good representation of the variable on the principal component. 
#In this case the variable is positioned close to the circumference of the correlation circle.
#A low cos2 indicates that the variable is not perfectly represented by the PCs. 
#In this case the variable is close to the center of the circle.

fviz_cos2(res.pca, choice = "var", axes = 1:2)
fviz_pca_var(res.pca, col.var = "cos2",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), 
             repel = TRUE # Avoid text overlapping
             )
# Change the transparency by cos2 values
fviz_pca_var(res.pca, alpha.var = "cos2")
corrplot(var$contrib, is.corr=FALSE)
# Contributions of variables to PC1
fviz_contrib(res.pca, choice = "var", axes = 1, top = 10)
# Contributions of variables to PC2
fviz_contrib(res.pca, choice = "var", axes = 2, top = 10)
fviz_pca_var(res.pca, col.var = "contrib",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07")
             )
fviz_pca_var(res.pca, alpha.var = "contrib")

fviz_pca_ind(res.pca,
             geom.ind = "point", # show points only (nbut not "text")
             col.ind = bm$Gender, # color by groups
             palette = c("#00AFBB", "#E7B800", "#FC4E07"),
             addEllipses = TRUE, # Concentration ellipses
             legend.title = "Groups"
             )
```


```{r}
# Description of PC

res.desc <- dimdesc(res.pca, axes = c(1,2,3,4,5), proba = 0.05)
# Description of dimension 1
res.desc$Dim.1
res.desc$Dim.2
res.desc$Dim.3
res.desc$Dim.4
res.desc$Dim.5

# Graph of Indiviuals
ind <- get_pca_ind(res.pca)
ind

## Principal Component Analysis Results for individuals
##  ===================================================
##   Name       Description                       
## 1 "$coord"   "Coordinates for the individuals" 
## 2 "$cos2"    "Cos2 for the individuals"        
## 3 "$contrib" "contributions of the individuals"
#To get access to the different components, use this:

# Coordinates of individuals
head(ind$coord)
# Quality of individuals
head(ind$cos2)
# Contributions of individuals
head(ind$contrib)
```

```{r}
fviz_pca_ind(res.pca)

fviz_pca_ind(res.pca, col.ind = "cos2", 
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE # Avoid text overlapping (slow if many points)
             )
fviz_pca_ind(res.pca, pointsize = "cos2", 
             pointshape = 21, fill = "#E7B800",
             repel = TRUE # Avoid text overlapping (slow if many points)
             )

fviz_pca_ind(res.pca, col.ind = "cos2", pointsize = "cos2",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE # Avoid text overlapping (slow if many points)
             )
fviz_cos2(res.pca, choice = "ind")
# Total contribution on PC1 and PC2
fviz_contrib(res.pca, choice = "ind", axes = 1:2)

# Create a random continuous variable of length 23,
# Same length as the number of active individuals in the PCA
set.seed(123)
my.cont.var <- rnorm(49)
# Color individuals by the continuous variable

```

```{r}
fviz_pca_ind(res.pca,
             geom.ind = "point", # show points only (nbut not "text")
             col.ind = bm$Gender, # color by groups
             palette = c("#00AFBB", "#E7B800", "#FC4E07"),
             addEllipses = TRUE, # Concentration ellipses
             legend.title = "Groups"
             )

fviz_pca_ind(res.pca, geom.ind = "point", col.ind = bm$Gender, 
             palette = c("#00AFBB", "#E7B800", "#FC4E07"),
             addEllipses = TRUE, ellipse.type = "confidence",
             legend.title = "Groups"
             )
fviz_pca_ind(res.pca,
             label = "none", # hide individual labels
             habillage = bm$Gender, # color by groups
             addEllipses = TRUE, # Concentration ellipses
             palette = "jco"
             )
fviz_pca_var(res.pca, geom.var = c("point", "text"))
# Show individuals text labels only
fviz_pca_ind(res.pca, geom.ind =  "text")
# Change the size of arrows an labels
fviz_pca_var(res.pca, arrowsize = 1, labelsize = 5, 
             repel = TRUE)
# Change points size, shape and fill color
# Change labelsize
fviz_pca_ind(res.pca, 
             pointsize = 3, pointshape = 21, fill = "lightblue",
             labelsize = 5, repel = TRUE)

fviz_pca_ind(res.pca,
             geom.ind = "point", # show points only (but not "text")
             group.ind = bm$Gender, # color by groups
             legend.title = "Groups",
             mean.point = FALSE)
fviz_pca_ind(res.pca,
             geom.ind = "point", # show points only (but not "text")
             group.ind = bm$Gender, # color by groups
             legend.title = "Groups",
             mean.point = TRUE)
fviz_pca_var(res.pca, axes.linetype = "blank")


```

```{r}
ind.p <- fviz_pca_ind(res.pca, geom = "point", col.ind = bm$Gender)
ggpubr::ggpar(ind.p,
              title = "Principal Component Analysis",
              subtitle = "Iris data set",
              caption = "Source: factoextra",
              xlab = "PC1", ylab = "PC2",
              legend.title = "Gender", legend.position = "top",
              ggtheme = theme_gray(), palette = "jco"
              )

fviz_pca_biplot(res.pca, repel = TRUE,col.ind = bm$Gender,
                col.var = "#2E9FDF", # Variables color
                )

fviz_pca_biplot(res.pca, 
                col.ind = bm$Gender, palette = "jco", 
                addEllipses = TRUE, label = "var",
                col.var = "black", repel = TRUE,
                legend.title = "Gender") 

fviz_pca_biplot(res.pca, 
                # Fill individuals by groups
                geom.ind = "point",
                pointshape = 21,
                pointsize = 2.5,
                fill.ind = bm$Gender,
                col.ind = "black",
                # Color variable by groups
                legend.title = list(fill = "Gender", color = "Clusters"),
                repel = TRUE        # Avoid label overplotting
             )+
  ggpubr::fill_palette("jco")+      # Indiviual fill color
  ggpubr::color_palette("npg")      # Variable colors

fviz_pca_biplot(res.pca, 
                # Individuals
                geom.ind = "point",
                fill.ind = bm$Gender, col.ind = "black",
                pointshape = 21, pointsize = 2,
                palette = "jco",
                addEllipses = TRUE,
                # Variables
                alpha.var ="contrib", col.var = "contrib",
                gradient.cols = "RdYlBu",
                
                legend.title = list(fill = "Gender", color = "Contrib",
                                    alpha = "Contrib")
                )

```

